# Dicionário de tradução de siglas para nomes de seleções
traducoesParaNome = {
    "ALG": "Argélia",
    "ARG": "Argentina",
    "AUS": "Austrália",
    "AUT": "Áustria",
    "BEL": "Bélgica",
    "BIH": "Bósnia e Herzegovina",
    "BRA": "Brasil",
    "CMR": "Camarões",
    "CHI": "Chile",
    "COL": "Colômbia",
    "CIV": "Costa do Marfim",
    "CRC": "Costa Rica",
    "CRO": "Croácia",
    "CZE": "República Tcheca",
    "DEN": "Dinamarca",
    "ECU": "Equador",
    "EGY": "Egito",
    "GHA": "Gana",
    "ENG": "Inglaterra",
    "ESP": "Espanha",
    "FRA": "França",
    "GER": "Alemanha",
    "GRE": "Grécia",
    "HON": "Honduras",
    "IRN": "Irã",
    "IRL": "Irlanda",
    "ISL": "Islândia",
    "ITA": "Itália",
    "JPN": "Japão",
    "KOR": "Coreia do Sul",
    "MAR": "Marrocos",
    "MEX": "México",
    "NED": "Holanda",
    "NGA": "Nigéria",
    "NZL": "Nova Zelândia",
    "PAN": "Panamá",
    "PER": "Peru",
    "POL": "Polônia",
    "POR": "Portugal",
    "RSA": "África do Sul",
    "RUS": "Rússia",
    "KSA": "Arábia Saudita",
    "SEN": "Senegal",
    "SRB": "Sérvia",
    "SUI": "Suíça",
    "SWE": "Suécia",
    "TUN": "Tunísia",
    "TUR": "Turquia",
    "UKR": "Ucrânia",
    "URU": "Uruguai",
    "USA": "Estados Unidos",
}