# Dicionário de tradução de nomes de seleções para siglas
traducoesParaSigla = {
    'Argélia': 'ALG',
    'Argentina': 'ARG',
    'Austrália': 'AUS',
    'Áustria': 'AUT',
    'Bélgica': 'BEL',
    'Bósnia e Herzegovina': 'BIH',
    'Brasil': 'BRA',
    'Camarões': 'CMR',
    'Chile': 'CHI',
    'Colômbia': 'COL',
    'Costa do Marfim': 'CIV',
    'Costa Rica': 'CRC',
    'Croácia': 'CRO',
    'República Tcheca': 'CZE',
    'Dinamarca': 'DEN',
    'Equador': 'ECU',
    'Egito': 'EGY',
    'Gana': 'GHA',
    'Inglaterra': 'ENG',
    'Espanha': 'ESP',
    'França': 'FRA',
    'Alemanha': 'GER',
    'Grécia': 'GRE',
    'Honduras': 'HON',
    'Irã': 'IRN',
    'Irlanda': 'IRL',
    'Islândia': 'ISL',
    'Itália': 'ITA',
    'Japão': 'JPN',
    'Coreia do Sul': 'KOR',
    'Marrocos': 'MAR',
    'México': 'MEX',
    'Holanda': 'NED',
    'Nigéria': 'NGA',
    'Nova Zelândia': 'NZL',
    'Panamá': 'PAN',
    'Peru': 'PER',
    'Polônia': 'POL',
    'Portugal': 'POR',
    'África do Sul': 'RSA',
    'Rússia': 'RUS',
    'Arábia Saudita': 'KSA',
    'Senegal': 'SEN',
    'Sérvia': 'SRB',
    'Suíça': 'SUI',
    'Suécia': 'SWE',
    'Tunísia': 'TUN',
    'Turquia': 'TUR',
    'Ucrânia': 'UKR',
    'Uruguai': 'URU',
    'Estados Unidos': 'USA'
}
